### ISSUE TITLE
[FE] 3차 스프린트 이후 Todo 기능 구현 (by 쿠키)

### ISSUE THREAD

**Issue by jinhokim98** [woowacourse-teams/2024-haeng-dong#304]
## 📄 설명

3차 데모데이 때 발견한 버그나 미구현 리스트를 구현해야합니다.

## 🏁 할 일

- [x] 차수 멤버 확인 기능 구현 → 쿠키
- [ ] Step에 차수 출력하기 → 쿠키
- [x] 에러 발생시(errorToast) FixedButton을 클릭해도 BottomSheet를 닫지 않기 → 쿠키
- [x] 입력된 사항이 없는데 FixedButton이 활성화 되어 있는 BottomSheet 수정 → 쿠키
